// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: internal/proto/taskmaster.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_UNKNOWN   Status = 0
	Status_UNSTARTED Status = 1
	Status_STARTING  Status = 2
	Status_RUNNING   Status = 3
	Status_STOPPING  Status = 4
	Status_STOPPED   Status = 5
	Status_ERRORED   Status = 6
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "UNSTARTED",
		2: "STARTING",
		3: "RUNNING",
		4: "STOPPING",
		5: "STOPPED",
		6: "ERRORED",
	}
	Status_value = map[string]int32{
		"UNKNOWN":   0,
		"UNSTARTED": 1,
		"STARTING":  2,
		"RUNNING":   3,
		"STOPPING":  4,
		"STOPPED":   5,
		"ERRORED":   6,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_taskmaster_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_internal_proto_taskmaster_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_taskmaster_proto_rawDescGZIP(), []int{0}
}

type Program struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Program) Reset() {
	*x = Program{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_taskmaster_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Program) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Program) ProtoMessage() {}

func (x *Program) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_taskmaster_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Program.ProtoReflect.Descriptor instead.
func (*Program) Descriptor() ([]byte, []int) {
	return file_internal_proto_taskmaster_proto_rawDescGZIP(), []int{0}
}

func (x *Program) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ProgramDesc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status Status `protobuf:"varint,2,opt,name=status,proto3,enum=Status" json:"status,omitempty"`
}

func (x *ProgramDesc) Reset() {
	*x = ProgramDesc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_taskmaster_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProgramDesc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgramDesc) ProtoMessage() {}

func (x *ProgramDesc) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_taskmaster_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgramDesc.ProtoReflect.Descriptor instead.
func (*ProgramDesc) Descriptor() ([]byte, []int) {
	return file_internal_proto_taskmaster_proto_rawDescGZIP(), []int{1}
}

func (x *ProgramDesc) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProgramDesc) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_UNKNOWN
}

type ProgramDescList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Programs []*ProgramDesc `protobuf:"bytes,1,rep,name=programs,proto3" json:"programs,omitempty"`
}

func (x *ProgramDescList) Reset() {
	*x = ProgramDescList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_taskmaster_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProgramDescList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgramDescList) ProtoMessage() {}

func (x *ProgramDescList) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_taskmaster_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgramDescList.ProtoReflect.Descriptor instead.
func (*ProgramDescList) Descriptor() ([]byte, []int) {
	return file_internal_proto_taskmaster_proto_rawDescGZIP(), []int{2}
}

func (x *ProgramDescList) GetPrograms() []*ProgramDesc {
	if x != nil {
		return x.Programs
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_taskmaster_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_taskmaster_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_internal_proto_taskmaster_proto_rawDescGZIP(), []int{3}
}

var File_internal_proto_taskmaster_proto protoreflect.FileDescriptor

var file_internal_proto_taskmaster_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x74, 0x61, 0x73, 0x6b, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x1d, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0x42, 0x0a, 0x0b, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x44, 0x65, 0x73, 0x63, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x07, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x22, 0x3b, 0x0a, 0x0f, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x44,
	0x65, 0x73, 0x63, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x67, 0x72,
	0x61, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x50, 0x72, 0x6f, 0x67,
	0x72, 0x61, 0x6d, 0x44, 0x65, 0x73, 0x63, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d,
	0x73, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x2a, 0x67, 0x0a, 0x06, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10,
	0x00, 0x12, 0x0d, 0x0a, 0x09, 0x55, 0x4e, 0x53, 0x54, 0x41, 0x52, 0x54, 0x45, 0x44, 0x10, 0x01,
	0x12, 0x0c, 0x0a, 0x08, 0x53, 0x54, 0x41, 0x52, 0x54, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x12, 0x0b,
	0x0a, 0x07, 0x52, 0x55, 0x4e, 0x4e, 0x49, 0x4e, 0x47, 0x10, 0x03, 0x12, 0x0c, 0x0a, 0x08, 0x53,
	0x54, 0x4f, 0x50, 0x50, 0x49, 0x4e, 0x47, 0x10, 0x04, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x54, 0x4f,
	0x50, 0x50, 0x45, 0x44, 0x10, 0x05, 0x12, 0x0b, 0x0a, 0x07, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x45,
	0x44, 0x10, 0x06, 0x32, 0x90, 0x02, 0x0a, 0x0a, 0x54, 0x61, 0x73, 0x6b, 0x6d, 0x61, 0x73, 0x74,
	0x65, 0x72, 0x12, 0x22, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x06, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x1a, 0x10, 0x2e, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x44, 0x65, 0x73, 0x63,
	0x4c, 0x69, 0x73, 0x74, 0x22, 0x00, 0x12, 0x1a, 0x0a, 0x06, 0x52, 0x65, 0x6c, 0x6f, 0x61, 0x64,
	0x12, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x22, 0x00, 0x12, 0x18, 0x0a, 0x04, 0x53, 0x74, 0x6f, 0x70, 0x12, 0x06, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x1a, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x29, 0x0a, 0x0d,
	0x50, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x08, 0x2e,
	0x50, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x1a, 0x0c, 0x2e, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x61,
	0x6d, 0x44, 0x65, 0x73, 0x63, 0x22, 0x00, 0x12, 0x28, 0x0a, 0x0c, 0x50, 0x72, 0x6f, 0x67, 0x72,
	0x61, 0x6d, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x08, 0x2e, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x61,
	0x6d, 0x1a, 0x0c, 0x2e, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x44, 0x65, 0x73, 0x63, 0x22,
	0x00, 0x12, 0x27, 0x0a, 0x0b, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x53, 0x74, 0x6f, 0x70,
	0x12, 0x08, 0x2e, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x1a, 0x0c, 0x2e, 0x50, 0x72, 0x6f,
	0x67, 0x72, 0x61, 0x6d, 0x44, 0x65, 0x73, 0x63, 0x22, 0x00, 0x12, 0x2a, 0x0a, 0x0e, 0x50, 0x72,
	0x6f, 0x67, 0x72, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x08, 0x2e, 0x50,
	0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x1a, 0x0c, 0x2e, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d,
	0x44, 0x65, 0x73, 0x63, 0x22, 0x00, 0x42, 0x2a, 0x5a, 0x28, 0x70, 0x6b, 0x67, 0x2e, 0x63, 0x6f,
	0x75, 0x6c, 0x6f, 0x6e, 0x2e, 0x64, 0x65, 0x76, 0x2f, 0x74, 0x61, 0x73, 0x6b, 0x6d, 0x61, 0x73,
	0x74, 0x65, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_proto_taskmaster_proto_rawDescOnce sync.Once
	file_internal_proto_taskmaster_proto_rawDescData = file_internal_proto_taskmaster_proto_rawDesc
)

func file_internal_proto_taskmaster_proto_rawDescGZIP() []byte {
	file_internal_proto_taskmaster_proto_rawDescOnce.Do(func() {
		file_internal_proto_taskmaster_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_proto_taskmaster_proto_rawDescData)
	})
	return file_internal_proto_taskmaster_proto_rawDescData
}

var file_internal_proto_taskmaster_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_proto_taskmaster_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_proto_taskmaster_proto_goTypes = []interface{}{
	(Status)(0),             // 0: Status
	(*Program)(nil),         // 1: Program
	(*ProgramDesc)(nil),     // 2: ProgramDesc
	(*ProgramDescList)(nil), // 3: ProgramDescList
	(*Empty)(nil),           // 4: Empty
}
var file_internal_proto_taskmaster_proto_depIdxs = []int32{
	0, // 0: ProgramDesc.status:type_name -> Status
	2, // 1: ProgramDescList.programs:type_name -> ProgramDesc
	4, // 2: Taskmaster.List:input_type -> Empty
	4, // 3: Taskmaster.Reload:input_type -> Empty
	4, // 4: Taskmaster.Stop:input_type -> Empty
	1, // 5: Taskmaster.ProgramStatus:input_type -> Program
	1, // 6: Taskmaster.ProgramStart:input_type -> Program
	1, // 7: Taskmaster.ProgramStop:input_type -> Program
	1, // 8: Taskmaster.ProgramRestart:input_type -> Program
	3, // 9: Taskmaster.List:output_type -> ProgramDescList
	4, // 10: Taskmaster.Reload:output_type -> Empty
	4, // 11: Taskmaster.Stop:output_type -> Empty
	2, // 12: Taskmaster.ProgramStatus:output_type -> ProgramDesc
	2, // 13: Taskmaster.ProgramStart:output_type -> ProgramDesc
	2, // 14: Taskmaster.ProgramStop:output_type -> ProgramDesc
	2, // 15: Taskmaster.ProgramRestart:output_type -> ProgramDesc
	9, // [9:16] is the sub-list for method output_type
	2, // [2:9] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_proto_taskmaster_proto_init() }
func file_internal_proto_taskmaster_proto_init() {
	if File_internal_proto_taskmaster_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_proto_taskmaster_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Program); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_taskmaster_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProgramDesc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_taskmaster_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProgramDescList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_taskmaster_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_proto_taskmaster_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_taskmaster_proto_goTypes,
		DependencyIndexes: file_internal_proto_taskmaster_proto_depIdxs,
		EnumInfos:         file_internal_proto_taskmaster_proto_enumTypes,
		MessageInfos:      file_internal_proto_taskmaster_proto_msgTypes,
	}.Build()
	File_internal_proto_taskmaster_proto = out.File
	file_internal_proto_taskmaster_proto_rawDesc = nil
	file_internal_proto_taskmaster_proto_goTypes = nil
	file_internal_proto_taskmaster_proto_depIdxs = nil
}
